name: first workflow
on:
  repository_dispatch:
    types: [test]
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "feature"
    types: [opened, closed]
jobs:
  first-workflow-jop:
    name: first jop
    runs-on: ubuntu-latest
    steps:
      - name: run bash command
        run: ls
        shell: bash
      - name: action checkout
        uses: actions/checkout@v4
      - name: after checkout
        run: ls
        shell: bash
